"""Create tables

Revision ID: cf8b25f9a2dd
Revises: 
Create Date: 2024-08-07 15:09:39.633974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8b25f9a2dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('record_id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('record_owner_id', sa.UUID(), nullable=False),
    sa.Column('record', sa.Text(), nullable=False),
    sa.Column('last_update', sa.TIMESTAMP(), nullable=False, server_default=sa.func.now()),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('records_access',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('record_owner_id', sa.UUID(), nullable=False),
    sa.Column('user_access_id', sa.UUID(), nullable=False),
    sa.Column('rights', sa.String(), nullable=False)
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('records_access')
    op.drop_table('records')
    # ### end Alembic commands ###
